backend:
  name: git-gateway
  branch: master

development_overrides:
  backend:
    name: file-system
    api_root: 'http://localhost:8000/api'


media_folder: static/images
public_folder: /images

prefabs:
  partner: &partner_prefab
    - label: Name
      name: name
      widget: string
    - label: Logo
      name: logo
      widget: image
    - label: Homepage
      name: homepage
      widget: string

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: Intro
            name: intro
            widget: string
          - label: Action Network ID
            name: "actionNetworkId"
            widget: string
          - label: YouTube Video ID
            name: "youtubeVideoId"
            widget: string
          - label: Detail Cards
            name: detailCards
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
              - label: Text
                name: text
                widget: text
              - label: Link
                name: link
                widget: object
                fields:
                  - label: Label
                    name: label
                    widget: string
                  - label: URL
                    name: url
                    widget: string
          - label: Partner Groups
            name: partnerGroups
            widget: list
            fields:
              - label: Group Title
                name: title
                widget: string
              - label: Partners
                name: partners
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
                  - label: Homepage
                    name: homepage
                    widget: string
      - file: "src/pages/faq/index.md"
        label: "FAQ"
        name: "faq"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "faq-page"
          - label: Intro
            name: intro
            widget: string
          - label: Entries
            name: entries
            widget: list
            fields:
              - label: Question
                name: question
                widget: string
              - label: Answer
                name: answer
                widget: string