backend:
  name: test-repo

media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: Intro
            name: intro
            widget: string
          - label: YouTube Video ID
            name: "youtubeVideoId"
            widget: string
          - label: Action Network ID
            name: "actionNetworkId"
            widget: string
          - label: Twitter Embed Search
            name: "twitterEmbedSearch"
            widget: string
      - file: "src/pages/faq/index.md"
        label: "FAQ"
        name: "faq"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "faq-page"
          - label: Intro
            name: intro
            widget: string
          - label: Entries
            name: entries
            widget: list
            fields:
              - label: Question
                name: question
                widget: string
              - label: Answer
                name: answer
                widget: string