backend:
  name: git-gateway
  branch: master

development_overrides:
  backend:
    name: file-system
    api_root: 'http://localhost:8000/api'


media_folder: static/images
public_folder: /images

prefabs:
  faq_page: &faq_page_prefab
    - label: "Template Key"
      name: "templateKey"
      widget: "hidden"
      default: "faq-page"
    - label: Intro
      name: intro
      widget: string
    - label: Entries
      name: entries
      widget: list
      fields:
        - label: "Slug"
          name: "slug"
          widget: "string"
          required: true
          hint: >-
            A unique identifier for the question that is composed of letters, numbers, and hyphens that will allow visitors and hyperlinks to point to a specific question on the page. For example, if you fill this in as my-question-and-answer then you'll be able construct the URL https://changethedebate.org/faq#my-question-and-answer, and visitors to that URL will be immediately scrolled to this question.
        - label: Question
          name: question
          widget: string
        - label: Answer
          name: answer
          widget: string
  schedule_page: &schedule_page_prefab
    - label: "Template Key"
      name: "templateKey"
      widget: "hidden"
      default: "schedule-page"
    - label: "Primary Events"
      name: "primaryEvents"
      widget: "list"
      fields:
        - label: "Start Date"
          name: "startDate"
          widget: "date"
          required: true
          hint: "What day does the event start on?"
        - label: "End Date"
          name: "endDate"
          widget: "date"
          required: true
          hint: "What day does the even end on?"
        - label: "Name"
          name: "name"
          widget: "string"
          hint: "What is the name of the event? E.g. \"Summit\" or \"Debate Action\"."
        - label: "Info"
          name: "info"
          widget: "markdown"
          required: true
          hint: "Write a paragraph or two about this event."
        - label: "Image"
          name: "image"
          required: true
          widget: "image"
          hint: "Choose an image to represent this event."

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: Intro
            name: intro
            widget: string
          - label: Action Network ID
            name: "actionNetworkId"
            widget: string
          - label: YouTube Video ID
            name: "youtubeVideoId"
            widget: string
          - label: Detail Cards
            name: detailCards
            widget: list
            fields:
              - label: Image
                name: image
                widget: image
              - label: Text
                name: text
                widget: text
              - label: Link
                name: link
                widget: object
                fields:
                  - label: Label
                    name: label
                    widget: string
                  - label: URL
                    name: url
                    widget: string
          - label: Partner Groups
            name: partnerGroups
            widget: list
            fields:
              - label: Group Title
                name: title
                widget: string
              - label: Partners
                name: partners
                widget: list
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Logo
                    name: logo
                    widget: image
                  - label: Homepage
                    name: homepage
                    widget: string

      - file: "src/pages/faq/en.md"
        label: "FAQ (English)"
        name: "faq-en"
        fields: *faq_page_prefab
      - file: "src/pages/faq/es.md"
        label: "FAQ (Spanish)"
        name: "faq-es"
        fields: *faq_page_prefab
      - file: "src/pages/schedule/en.md"
        label: "Schedule (English)"
        name: "schedule-en"
        fields: *schedule_page_prefab
      - file: "src/pages/schedule/es.md"
        label: "Schedule (Spanish)"
        name: "schedule-es"
        fields: *schedule_page_prefab
