backend:
  name: git-gateway
  branch: master

development_overrides:
  backend:
    name: file-system
    api_root: 'http://localhost:8000/api'


media_folder: static/images
public_folder: /images

prefabs:
  home_page: &home_page_prefab
    - label: "Template Key"
      name: "templateKey"
      widget: "hidden"
      default: "index-page"
    - label: Intro
      name: intro
      widget: string
    - label: Action Network ID
      name: "actionNetworkId"
      widget: string
    - label: YouTube Video ID
      name: "youtubeVideoId"
      widget: string
    - label: Detail Cards
      name: detailCards
      widget: list
      fields:
        - label: Image
          name: image
          widget: image
        - label: Text
          name: text
          widget: text
        - label: Link
          name: link
          widget: object
          fields:
            - label: Label
              name: label
              widget: string
            - label: URL
              name: url
              widget: string
    - label: Partner Groups
      name: partnerGroups
      widget: list
      fields:
        - label: Group Title
          name: title
          widget: string
        - label: Partners
          name: partners
          widget: list
          fields:
            - label: Name
              name: name
              widget: string
            - label: Logo
              name: logo
              widget: image
            - label: Homepage
              name: homepage
              widget: string
  faq_page: &faq_page_prefab
    - label: "Template Key"
      name: "templateKey"
      widget: "hidden"
      default: "faq-page"
    - label: Intro
      name: intro
      widget: string
    - label: Entries
      name: entries
      widget: list
      fields:
        - label: "Slug"
          name: "slug"
          widget: "string"
          required: true
          hint: >-
            A unique identifier for the question that is composed of letters, numbers, and hyphens that will allow visitors and hyperlinks to point to a specific question on the page. For example, if you fill this in as my-question-and-answer then you'll be able construct the URL https://changethedebate.org/faq#my-question-and-answer, and visitors to that URL will be immediately scrolled to this question.
        - label: Question
          name: question
          widget: string
        - label: Answer
          name: answer
          widget: string
  schedule_page: &schedule_page_prefab
    - label: "Template Key"
      name: "templateKey"
      widget: "hidden"
      default: "schedule-page"
    - label: "Actions"
      name: "actions"
      widget: "list"
      fields:
        - label: "Name"
          name: "name"
          widget: "string"
          hint: "What is the name of the action? E.g. \"Summit\" or \"Debate Action\"."
        - label: "Start Date"
          name: "startDate"
          widget: "date"
          required: true
          hint: "What day does the action start on?"
        - label: "End Date"
          name: "endDate"
          widget: "date"
          required: true
          hint: "What day does the action end on?"
        - label: "Info"
          name: "info"
          widget: "markdown"
          required: true
          hint: "Write a paragraph or two about this event."
        - label: "Image"
          name: "image"
          required: true
          widget: "image"
          hint: "Choose an image to represent this event."
        - label: "Events"
          name: "events"
          hint: "What events will take place as a part of this action?"
          widget: "list"
          allow_add: true
          fields:
            - label: "Name"
              name: "name"
              required: true
              hint: "What is the name of this event?"
              widget: "string"
            - label: "Start Time"
              name: "startTime"
              required: true
              hint: "What day and time will this event start?"
              widget: "datetime"
            - label: "End Time"
              name: "endTime"
              required: true
              hint: "What day and time will this event end?"
              widget: "datetime"
            - label: "Details"
              name: "details"
              required: true
              hint: "What should people know about this event?"
              widget: "markdown"
            - label: "Location"
              name: "location"
              required: true
              hint: "Where should people go to attend this event?"
              widget: "object"
              fields:
                - label: "Name"
                  name: "name"
                  required: true
                  hint: "What is the name of the place?"
                  widget: "string"
                - label: "Address"
                  name: "address"
                  required: true
                  hint: "Write out the address or description of the place."
                  widget: "string"
            - label: "Contact"
              name: "contact"
              required: true
              hint: "Who can people contact to get help with this event?"
              widget: "object"
              fields:
                - label: "Name"
                  name: "name"
                  required: true
                  hint: "What is the name of the person or team people should talk to for help?"
                  widget: "string"
                - label: "Phone"
                  name: "phone"
                  required: true
                  hint: "What phone number should people call?"
                  widget: "string"
                - label: "Email"
                  name: "email"
                  required: true
                  hint: "What email address should people contact?"
                  widget: "string"

collections:
  - name: "config"
    label: "Config"
    files:
      - file: "static/site/config.md"
        label: "Site Config"
        name: "site-config"
        fields:
          - label: "Is Config"
            name: "isConfig"
            required: true
            default: true
            widget: "hidden"
          - label: "Donation Link"
            name: "donationLink"
            required: true
            hint: "Where does the donate link lead?"
            widget: "string"
          - label: "Time Zone"
            name: "timezone"
            required: true
            hint: "What timezone should dates and times display in?"
            widget: "select"
            options:
              - "America/Detroit"
              - "UTC"
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/en.md"
        label: "Home Page (English)"
        name: "home-en"
        fields: *home_page_prefab
      - file: "src/pages/home/es.md"
        label: "Home Page (Spanish)"
        name: "home-es"
        fields: *home_page_prefab
      - file: "src/pages/faq/en.md"
        label: "FAQ (English)"
        name: "faq-en"
        fields: *faq_page_prefab
      - file: "src/pages/faq/es.md"
        label: "FAQ (Spanish)"
        name: "faq-es"
        fields: *faq_page_prefab
      - file: "src/pages/schedule/en.md"
        label: "Schedule (English)"
        name: "schedule-en"
        fields: *schedule_page_prefab
      - file: "src/pages/schedule/es.md"
        label: "Schedule (Spanish)"
        name: "schedule-es"
        fields: *schedule_page_prefab
