backend:
  name: test-repo

media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "index-page"
          - label: Intro
            name: intro
            widget: string
          - label: YouTube Video ID
            name: "youtubeVideoId"
            widget: string
          - label: Action Network ID
            name: "actionNetworkId"
            widget: string
          - label: Partners
            name: partners
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Logo
                name: logo
                widget: image
              - label: Homepage
                name: homepage
                widget: string
              - label: Level
                name: level
                widget: select
                options:
                  - { label: "Host by", value: "host" }
                  - { label: "With support from", value: "national_partner" }
                  - { label: "Additional supporters", value: "additional_supporter" }
      - file: "src/pages/faq/index.md"
        label: "FAQ"
        name: "faq"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "faq-page"
          - label: Intro
            name: intro
            widget: string
          - label: Entries
            name: entries
            widget: list
            fields:
              - label: Question
                name: question
                widget: string
              - label: Answer
                name: answer
                widget: string